package com.ewerp.mud.sessions.terminal;

import com.ewerp.mud.commands.ICommand;
import com.ewerp.mud.commands.IMessage;
import com.ewerp.mud.plugins.ILifecycleListener;
import com.ewerp.mud.plugins.IPluginManager;
import com.ewerp.mud.sessions.ISession;

import java.net.Socket;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Copyright 2012 Curtis Boyden
 * <p/>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p/>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p/>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The {@link TerminalSession} wraps a socket connection and provides an interface between a Terminal
 * connection and the {@link ICommand} / {@link IMessage} system.
 *
 * {@link TerminalSession}s are generated by the {@link TerminalSessionFactory} when a new socket
 * connection is detected.
 */
public class TerminalSession implements ISession, Runnable {
    protected Thread sessionThread;
    protected Socket socket;

    protected AtomicBoolean shutdown = new AtomicBoolean(false);

    protected IPluginManager pluginManager;

    public TerminalSession(Socket socket) {
        this.socket = socket;
        this.sessionThread = new Thread(this);

        this.sessionThread.start();
    }

    @Override
    public void setPluginManager(IPluginManager pluginManager) {
        this.pluginManager = pluginManager;
    }

    // Close socket connection gracefully per a standard terminal connection
    @Override
    public void shutdown() {
        shutdown.set(true);
        sessionThread.interrupt();
    }

    /**
     * Pass the message through a chain of linkable interpreters
     * @param message {@link IMessage} (generated by a commands) to be interpreted for the session client
     */
    @Override
    public void processMessage(IMessage message) {
    }

    @Override
    public void run() {
    }
}
